### ISSUE TITLE
Implement package_show and package_show_revision actions in logic layer

### ISSUE THREAD

**Issue by rufuspollock** [datopian/ckanext-versioning#10]
When accessing a package through CKAN logic layer I want to see latest revision of package and be able to get older revisions so that I can display through API or WuI

Refactor ckanext-versions **package show override** for new metastore `package_show_version`

Est: 2d

* change logic function package_show which currently in ckanext-versions calls package_show_revision (and hence vdm) to use new metastore
* b/c we pull metadata cleanly from the new Metastore we may need to add some fields back in for HEAD like datastore_active ... (i.e. dict merge from CKAN main db)
* 🚩 avoid "showcase" packages

## Acceptance

* [x] Calling `package_show` (with no revision) is unchanged from today
  * NB: AFAICT API does not support passing revision id (or its undocumented) https://docs.ckan.org/en/2.8/api/index.html#ckan.logic.action.get.package_show
* [x] New `package_show_revision` action that supports calling with revisions and this returns same as `package_show` but with correct metadata for old revision
  * NB: package core metadata (ie. on a package) and resource will have "correct" older info but e.g. groups, owner etc will have metadata from master
  * TODO: make sure we document this so it is clear ...

## Tasks

* [x] Research our approach to implementation
  * [x] Metadata retrieval and merging
  * [x] Plugin point **ANS: Override `package_show` action and add now `package_show_revision` action**
* [x] `package_show` (with no revision id)
  * [x] Call base `package_show`
  * [ ] ~~Copy over ckanext-versions `package_show`~~
* [x] `package_show` with revision id => call `package_show_revision`

## Analysis

We largely follow existing ckanext-versions approach:

https://github.com/datopian/ckanext-versioning/blob/9a38b54f22def2e22dc64d79e2c4b182d3b226f0/ckanext/versioning/logic/action.py#L259 

### What is algorithm for `package_show`? (with / without revision)

* Override `package_show` action in our extension
* Have it call a new `package_show_revision`
* That works as follows:
  * If no revision then just call core package_show
    * If we wanted to be thorough we could load from git and then do some stuff ... BUT we don't!
  * If a revision: see options below

There a few options for how we could proceed when we hae a revision:

1. Load from package_show in core and overwrite with some of the revision metadata
   * Pros: least work
   * Cons: what about e.g. resource links ... => have to hack them ... as per https://gitlab.com/datopian/ckanext-versions/-/blob/develop/ckanext/versions/logic/action.py#L329
2. Load from metastore lib and enhance ❌ **probably painful and end up replicating code in existing show**
3. have a separate controller and template ❌ **good idea but more work atm**
   * Pros: cleaner, long-term approach to designing the showcase page
   * Cons: more work e.g. you have duplicate templates, ...

### How to load from metastore

```mermaid
graph TD

metastore --> convert[Convert to core CKAN structure i.e. as_dict like]
convert --> convert2[Convert to package_show structure]
convert2 --> merge[Merge into result of package_show]
```

### Core package_show: 

https://github.com/ckan/ckan/blob/ckan-2.8.4/ckan/logic/action/get.py#L962

Summary

* Loads object from DB via id
* Checks access
* Include Tracking
* Decide if using Cache (Solr)
* Plugins Interfaces

### Showcase Show 

https://github.com/ckan/ckanext-showcase/blob/00b019b96b260d0fa6b93d511c1580dec5322bd3/ckanext/showcase/controller.py#L40

### Showcase page rendering discussion (desired - future)

Qu: how do you combine general content (e.g. link to issue trackers), content for master (e.g. stats) and revision related content

cf github where some stuff stays related to master even on older version

Master

![](https://i.imgur.com/swFKjUE.png)

Older revision

![](https://i.imgur.com/eSb16ET.png)

```mermaid
graph LR

project[General   Project info]
current[Dataset / Project current state]
specific[Specific to state at that point in time]

project --> menu
project --> title

current --> stats

specific --> display[Display of content e.g. metadata, descriptions]
```
