### ISSUE TITLE
[epic] Create ckanext-versioning by refactoring existing ckanext-versions and ckanext-gitdatahub for new metastore

### ISSUE THREAD

**Issue by rufuspollock** [datopian/ckanext-versioning#3]
New versioning system (revisions and tags) with new new git-based metastore https://github.com/datopian/metastore-lib.

Est: 10d

## Acceptance

See subtasks for detailed acceptance 

* [x] Package create, update etc results in calls to MetaStore - see #8
* [x] package_show and package_show_revision works ...
* [x] Porcelain works

In summary: Calling these functions from original action system work 😉

```
'dataset_version_create': action.dataset_version_create,
'dataset_version_delete': action.dataset_version_delete,
'dataset_version_list': action.dataset_version_list,
'dataset_version_update': action.dataset_version_update,
'dataset_version_show': action.dataset_version_show,
'dataset_version_promote': action.dataset_version_promote,
'package_show_version': action.package_show_version,
'resource_show_version': action.resource_show_version,
'dataset_versions_diff': action.dataset_versions_diff,

# Overridden
'package_show': action.package_show_revision,
'resource_show': action.resource_show_revision
```

## Tasks

* [x]  Boot a new ckanext-versioning in github and push current ckanext-versions code there. Do rename to ckanext-versioning (0.25d) 
* [x] Update functionality working - Refactor write functionality in ckanext-gitdatahub to use new MetaStore and merge into ckanext-versioning @pdelboca io (3.25d). Merge in existing code and refactor for. 
* [x] Package show working: Refactor ckanext-versions `package_show` work for new metastore @patricio 2d #10
* [x] Refactor ckanext-versions version logic layer to use new metastore (1.5d)
  ```
  dataset_version_list
  dataset_version_show
  dataset_version_delete
  ```
* [x] Porcelain (2d)
  * [x] Revision diffing
  * [x] Promote/revert functionality
* [x] ckanext-versioning: misc tidying and refactoring 2d
  * [x] Remove uploader plugin.py and https://gitlab.com/datopian/ckanext-versions/-/blob/develop/ckanext/versions/logic/uploader.py
    * Why? Because this was part of attempt to do data versioning in the old way and we now do direct data upload. TODO: check with @shahar
  * [x] Maybe other stuff ...

### ckanext-versions

https://gitlab.com/datopian/ckanext-versions/-/tree/develop/ckanext/versions

* [ ] https://gitlab.com/datopian/ckanext-versions/-/blob/develop/ckanext/versions/blueprints.py => has changes (show diff) function and blueprint
* [ ] https://gitlab.com/datopian/ckanext-versions/-/blob/develop/ckanext/versions/model.py - single table DatasetVersion
  * 🚩 it has `creator_user_id = Column(UuidType, ForeignKey('user.id'), nullable=False)` => make sure MetaStore tag function takes and gives back user info (name and/or email). NB github API supports this https://developer.github.com/v3/git/tags/#create-a-tag-object. Suggestion: that either email is sufficient *OR* we do something `name: Joe Bloggs <ckan_username: joebloggs>` or just `name: {ckan_user_name}` e.g. `name: joebloggs` or `name: userid`
* [ ] plugin.py https://gitlab.com/datopian/ckanext-versions/-/blob/develop/ckanext/versions/plugin.py#L49
```
    def get_actions(self):
        return {
            'dataset_version_create': action.dataset_version_create,
            'dataset_version_delete': action.dataset_version_delete,
            'dataset_version_list': action.dataset_version_list,
            'dataset_version_update': action.dataset_version_update,
            'dataset_version_show': action.dataset_version_show,
            'dataset_version_promote': action.dataset_version_promote,
            'package_show_version': action.package_show_version,
            'resource_show_version': action.resource_show_version,
            'dataset_versions_diff': action.dataset_versions_diff,

            # Overridden
            'package_show': action.package_show_revision,
            'resource_show': action.resource_show_revision
        }

# ~rufus - this is part where either you go full in on metastore auth or stick with this ...
# depends on option 1 or 2

    # IAuthFunctions

    def get_auth_functions(self):
        return {
            'dataset_version_create': auth.dataset_version_create,
            'dataset_version_delete': auth.dataset_version_delete,
            'dataset_version_list': auth.dataset_version_list,
            'dataset_version_show': auth.dataset_version_show,
            'dataset_versions_diff': auth.dataset_versions_diff,
        }

    # ITemplateHelpers

    def get_helpers(self):
        return {
            'url_for_version': helpers.url_for_version,
            'url_for_resource_version': helpers.url_for_resource_version,
            'dataset_version_has_link_resources': helpers.has_link_resources,
            'dataset_version_compare_pkg_dicts': helpers.compare_pkg_dicts,
        }

# some parts of this are hacky! maybe we do *some* of option 1 even if not all!!

    # IPackageController

    def before_view(self, pkg_dict):
        try:
            versions = action.dataset_version_list({"ignore_auth": True},
                                                   {"dataset": pkg_dict['id']})
        except toolkit.ObjectNotFound:
            # Do not blow up if package is gone
            return pkg_dict

        toolkit.c.versions = versions

        version_id = toolkit.request.params.get('version', None)
        if version_id:
            version = action.dataset_version_show({"ignore_auth": True},
                                                  {"id": version_id})
            toolkit.c.current_version = version

            # Hide package creation / update date if viewing a specific version
            pkg_dict['metadata_created'] = None
            pkg_dict['metadata_updated'] = None
        return pkg_dict

    # IBlueprint

    def get_blueprint(self):
        return [blueprints.versions]

    # IResourceController

    def before_delete(self, context, resource, resources):
        pass

    # IUploader

    def get_resource_uploader(self, data_dict):
        return uploader.get_uploader(self, data_dict)

# ~rufus why is this needed? Is this a way to enforce revisioning when data file changed?

    # IDatasetForm

    def update_package_schema(self):
        schema = super(VersionsPlugin, self).update_package_schema()
        schema['resources'].update(
            {UPLOAD_TS_FIELD: [
                toolkit.get_validator('ignore_missing'),
                toolkit.get_converter('convert_to_extras')
            ]}
        )
        return schema

    def show_package_schema(self):
        schema = super(VersionsPlugin, self).show_package_schema()
        schema['resources'].update(
            {UPLOAD_TS_FIELD: [
                toolkit.get_converter('convert_from_extras'),
                toolkit.get_validator('ignore_missing')
            ]}
        )
        return schema

    def is_fallback(self):
        return False

    def package_types(self):
        return []

    # IResourceController

    def before_create(self, context, data_dict):
        return self._set_upload_timestamp(data_dict)

    def before_update(self, context, current, data_dict):
        return self._set_upload_timestamp(data_dict, current)

    def _set_upload_timestamp(self, data_dict, current=None):
        """When creating or updating a resource, if it contains a file upload,
        save the upload timestamp as a resource extra field
        """
        if isinstance(data_dict.get('upload'), ALLOWED_UPLOAD_TYPES):
            ts = datetime.now().isoformat()
            log.debug("Setting upload timestamp to %s=%s", UPLOAD_TS_FIELD, ts)
            data_dict[UPLOAD_TS_FIELD] = ts
        elif data_dict.get('clear_upload') and UPLOAD_TS_FIELD in data_dict:
            log.debug("Clearing upload timestamp field")
            del data_dict[UPLOAD_TS_FIELD]
        elif current and UPLOAD_TS_FIELD in current:
            data_dict[UPLOAD_TS_FIELD] = current[UPLOAD_TS_FIELD]
        return data_dict
```

## Analysis re Do we have CKAN Classic logic functions and API for tagging and package_show_revision or not?

**Decision atm: Use Option 2 - b/c we think less risky for now (it's more a refactor approach)**

* Option 1: chuck out ckanext-versions API / logic layer  and refactor CKAN package show + version/revision controller + JS to use metastore
  * option: refactor logic package_show_version and still use that for read controllers
* Option 2: refactor logic layer and then (hope) we do (almost) nothing on the UI ...

Pros of option 1:

* Cleaner ckanext-versions e.g. we avoid the nasty stuff happening atm in ckanext-versions logic layer e.g. deleting "datastore_active"
* UI is "cleaner" 
  * can be dropped into other projects without ckanext-versions frontend

Cons

* Have to do work on UI layer
  * have to rewrite javascript a bit including getting a token
  * have to have new blueprints for view pages (see below)

#### Option 1

Chuck out these functions

```
dataset_version_list
dataset_version_show
dataset_version_delete
package_show_version
```

/dataset/xyz => this can be HEAD
  * listing revisions + tags go to javascript
/dataset/xyz@revision
  * write a new blueprint and that controller can data processing
  * get raw data
  * process that to dict needed for a clean template
  * give it to the template
dataset/resource/uuid@revision
  * write a new blueprint

We don't have to have it look exactly the same! After all it already does not e.g. datastore and previews.

**Comment by rufuspollock** [comment]
FIXED. Everything done - all items checked and we are live with this.
