### ISSUE TITLE
[epic] UI refactor of ckanext-versions

### ISSUE THREAD

**Issue by rufuspollock** [datopian/ckanext-versioning#4]
We anticipate relatively little work is needed here because we are preserving the existing ckanext-versions API.

Est: 2d

## URL Design

```
# url structure
/dataset/myname/ => [implicitly] /dataset/myname/show/default/ # default-branch-latest-revision/
/dataset/myname/resource/xxx => [implicitly] renders  /dataset/myname/show/default/{resource-id}

# explicit revisions
/dataset/myname/show/{revref}/              # dataset showcase
/dataset/myname/show/{revref}/{resource-id} # resource showcase
```

Future (not now)

```
# releases (optional) - NOT NEEDED since "inlining"
/dataset/myname/releases

# revisions
/dataset/myname/revisions 
```

## Acceptance

Showcase

* [x] `/dataset/xxx` works and NO longer supports @ functionality and displays result of package_show
  * [x] Page also has release links
    * [x] "releases" (revision tags)  go to release pages
    * [x] there is a direct link to revision of that dataset => /dataset/xxx/show/{revref} cf github
        
       You are basically inlining this kind of listing in dataset page ![](https://i.imgur.com/hqRyZon.png)
* [x] `/dataset/xxx/show/{revref}/` works and shows dataset at revref
* [x] `/dataset/xxx/resource/yyy` works ... (i.e. is an alias to master)
  * [x] `/dataset/xxx/show/{revref}/{resource-id}` works and shows resource at revref
* [ ] Add in README: if you use ckanext-versioning you can no longer access revisions via this kind of url (why? See this issue ...): `/dataset/myname@xxxx` Instead revision access is now explicit and reference url structure
* [x] Managing revision tags in UI work: All UI functions to create, list and delete revision tags work.

## Tasks

* [x] Create our own package read controller method so that we can control presentation and remove the `@revid` stuff
  * [x] Do as much "hacky" presentation stuff in the controller as we can not in the action e.g. making resource paths work when at a revision ...
  * [ ] ~~Explicitly look up revision tags separate from the package lookup~~ Done in JS so no need.
* [x] Create routes (reuse package show template) for revref
* [ ] ~~Create releases page~~

BONUS

* [ ] Create list revisions page

## Analysis

Options:

* Mess around in package_show action (and other ways) b/c of issue of passing revision_ref => see below "why we have to do something"
* Replace package read controller

Go for refactor read controller ... because

* We can remove current `@` behaviour and have cleaner setup for the future
* We want to managle resource urls to link right revref ...

### Why we have to do something

* If we are not changing existing CKAN controllers for urls /dataset/xxx/ page
* They parse the url and it it has an `@` it they parse out string after the `@` and pass it as `revision_id` key in the context object
* Current parse algorith for url strings e.g. `xxxx@yyyy` is here https://github.com/ckan/ckan/blob/7900935de6270ee80ec64a5378251dafedf3a0e4/ckan/controllers/package.py#L367
  * It first check if `yyyy` is a UUID
  * If not it attempts to parse as a date
  * If that fails it errors
  * => this **only** accept `revision_id` as CKAN UID or timestamp as valid formats
* So, how do we implement `package_show_revision(context, data_dict)` to call `core_package_show` or our internal `_get_package_in_revision(context, dd, revision_date)` if we cannot pass the `revision_ref` (commit id) from the controller to the action.
* => a problem. So ANS: we don't!

```
# url structure
/dataset/myname/ => [implicitly] /dataset/myname/show/master/
/dataset/myname/resource/xxx
  => [implicitly] renders  /dataset/myname/show/master/{resource-id}

/dataset/myname/show/{revref}/              # dataset showcase
/dataset/myname/show/{revref}/{resource-id} # resource showcase
```

IGNORE

```
# IGNORE: FUTURE MAYBE if we wanted to follow gitlab
/dataset/myname/-/show/{revref}/[{path-or-name-or-position in resource array}]
/dataset/myname/-/resource/{revref}/{resourceid}

# ? query string option ❌
/dataset/myname/?revision=...
/dataset/myname/resource/xxxx?revision=...
```

**Comment by rufuspollock** [comment]
@pdelboca when we close can we leave some kind of fixed message as https://playbook.datopian.com/issues-tasks/#closing-issues 🙏
