### ISSUE TITLE
[epic] Create and update package and resources in CKAN writes to Metastore

### ISSUE THREAD

**Issue by rufuspollock** [datopian/ckanext-versioning#8]
Create and update packages (and resources) in CKAN connects through to new MetaStore resulting in e.g. new revisions etc.

We plan to proceed by refactoring existing write functionality in ckanext-gitdatahub to use new MetaStore and merge this into ckanext-versioning

Est: 3.25d

## Acceptance

* [x] create **Implemented but needs tests and will need more work on conversion to Frictionless formats**
* [x] update **Implemented but needs tests and will need more work on conversion to Frictionless formats**
* [x] ~~delete (does nothing against metastore)~~ **Nothing needed 😉**
* [ ] purge (calls delete on metastore which removes datapackage.json but does not remove repo) **Not done as requires overriding controllers or similar as no logic layer for this**
  * 🚩 watch out for fact that we need to avoid writing showcases as datasets ... **DONE**

TODO: merge into above ...

* [x] create package results in MetaStore being called with right datapackage.json (which would then result => a new git repo is created in backend with datapackage.json etc but we don't need to test that here)
* [x] On updating a package MetaStore update is called with right Frictionless dict
* [x] Create resource on package results in MetaStore being called ...
* [x] Update resource results in ... 
* [x] delete (does nothing against metastore)
* [x] purge (calls delete on metastore which removes datapackage.json and removes repo)

Notes:

* 🚩 watch out for fact that we need to avoid writing showcases as datasets ...
* The big issue is the mocks etc - but that is done b4 in Metastore work

## Tasks

* [x] Research / analysis
  * [x] What is algorithm for package_create
  * [x] What is the metadata mapping
  * [x] Which plugin point do we use in CKAN? e.g. at action or controller layer?
* [x] Package.create
* [x] Package.update
* [x] Resource.create
* [x] Resource.update
* [x] Resource.XXX
* [x] Package.delete
* [ ] Package.purge

For each of these:

* [x] Create a test (and have it fail)
* [x] Make the test pass 

### What is the ckanext-versioning algorithm for package_create/update?

```mermaid
graph TD

actioncreate[Core `package_create`] --plugin link--> plugin[Plugin package_create]

subgraph "ckanext-versioning plugin"
  plugin --if package type--> ser1[Serialize 1 i.e. `as_dict`]
  ser1 --> ser2["Serialize 2: Enhance e.g. add path ..."]
  ser2 --> convert
  convert[Standard Convert to dp.json] --new dict--> metastore[Write to MetaStore using metastore-lib]
end
```

Pseudo-code

```python
def package_create():
  out1 = convfert(pkg)
  out2 = convertofrictionless(out1)
  metastorelib.save(out2)
```

### How does core package_create work

package_create: https://github.com/ckan/ckan/blob/7900935de6270ee80ec64a5378251dafedf3a0e4/ckan/logic/action/create.py#L46

* validates
* Create a model.Package object `pkg = model_save.package_dict_save(data, context)`
* Passes that pkg object to all the plugins

Link to model.package.Package
https://github.com/ckan/ckan/blob/7900935de6270ee80ec64a5378251dafedf3a0e4/ckan/model/package.py#L64

### What are the core Serialize (and unserialize) functions in CKAN for packages ...

* model.Package.as_dict() 
* https://github.com/ckan/ckan/blob/master/ckan/lib/dictization/model_dictize.py

Focus on former as more basic. Y/N/? indicate whether we use ...

```python=
def as_dict(self, ref_package_by='name', ref_group_by='name'):
Y    _dict = domain_object.DomainObject.as_dict(self)
    # Set 'license' in _dict to cater for old clients.
    # Todo: Remove from Version 2?
?    _dict['license'] = self.license.title if self.license else _dict.get('license_id', '')
    _dict['isopen'] = self.isopen()
    tags = [tag.name for tag in self.get_tags()]
    tags.sort() # so it is determinable
Y    _dict['tags'] = tags
N?    groups = [getattr(group, ref_group_by) for group in self.get_groups()]
    groups.sort()
    _dict['groups'] = groups
Y    _dict['extras'] = {key: value for key, value in self.extras.items()}
N    _dict['ratings_average'] = self.get_average_rating()
N    _dict['ratings_count'] = len(self.ratings)
Y    _dict['resources'] = [res.as_dict(core_columns_only=False) \
                          for res in self.resources]
    site_url = config.get('ckan.site_url', None)
N    if site_url:
        _dict['ckan_url'] = '%s/dataset/%s' % (site_url, self.name)
Y?    _dict['relationships'] = [rel.as_dict(self, ref_package_by=ref_package_by) for rel in self.get_relationships()]
Y    _dict['metadata_modified'] = self.metadata_modified.isoformat() \
        if self.metadata_modified else None
Y    _dict['metadata_created'] = self.metadata_created.isoformat() \
        if self.metadata_created else None
    import ckan.lib.helpers as h
N    _dict['notes_rendered'] = h.render_markdown(self.notes)
N    _dict['type'] = self.type or u'dataset'
    return _dict
```
